### ISSUE TITLE
can't run, broken RegExp ?

### ISSUE THREAD

**Issue by EricLanduyt** [brettz9/integrity-matters#2]
I recently had an error when simply trying to start integrity-matters (without even passing any arguments, or just -h) under node v16.10.0.
I suspect it might be linked to recently updated dependencies (as reported by npm audit).
```
$ npx integrity-matters -h
> node_modules/integrity-matters/src/common.js:4
>   return new RegExp(cliString, 'um');
>          ^
>
> SyntaxError: Invalid regular expression: /https://unpkg\.com/(?<name>[^@]*)@(?<version>v?)(?:(?:0|[1-9]\d{0,9})\.){2}(?:0|[1-9]\d{0,9})(?:-(?:0|[1-9]\d*?|[\da-z-]*?[a-z-][\da-z-]*?){0,100}(?:\.(?:0|[1-9]\d*?|[\d
a-z-]*?[a-z-][\da-z-]*?))*?){0,100}(?:\+[\da-z-]+?(?:\.[\da-z-]+?)*?){0,100}\b){1,20)(?<dist>/dist)?(?<path>[^ '"]*?)(?<slim>(?:\.slim)?)(?<min>(?:\.min)?)(?<ext>(?:\.(?:js|css))?)$/: Unmatched ')'
>     at new RegExp (<anonymous>)
>     at exports.basePathToRegex (node_modules/integrity-matters/src/common.js:4:10)
>     at node_modules/integrity-matters/src/index.js:83:10
>     at Array.map (<anonymous>)
>     at Object.<anonymous> (node_modules/integrity-matters/src/index.js:82:3)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by brettz9** [comment]
Yes, apologies for not getting to this yet--not feeling well, so should need some more time to get to this, but yeah, the regex we were using broke after an update--probably should peg to a specific patch version so this doesn't happen again...

**Comment by brettz9** [comment]
Please let me know if v0.14.0 does the trick for ya! Thanks and thanks for your patience on the delayed fix!

**Comment by EricLanduyt** [comment]
It is now working perfectly again, so thank you very much for the fix (and for such a quick reaction from my point of view) !
