### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by sbrunner** [brettz9/integrity-matters#3]
I try: 
- `npm i -D integrity-matters`
- `node_modules/.bin/integrity-matters --help`

And I get:
```
/home/sbrunner/workspace/tilecloud-chain/node_modules/update-notifier/index.js:36
                        throw new Error('pkg.name and pkg.version required');
                        ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (/home/sbrunner/workspace/tilecloud-chain/node_modules/update-notifier/index.js:36:10)
    at module.exports (/home/sbrunner/workspace/tilecloud-chain/node_modules/update-notifier/index.js:182:25)
    at exports.cliBasics (/home/sbrunner/workspace/tilecloud-chain/node_modules/command-line-basics/src/index.js:100:20)
    at Object.<anonymous> (/home/sbrunner/workspace/tilecloud-chain/node_modules/integrity-matters/bin/index.js:9:27)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.19.1
```

What did I wrong?

**Comment by brettz9** [comment]
This tool requires you have a `package.json` file with `name` and `version` properties. You can run `npm init` to be assisted in creating the file.

**Comment by sbrunner** [comment]
Effectively thanks :-)
